---
apiVersion: v1
kind: ImageStream
metadata:
  name: dev-conf-demo-app

---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: dev-conf-demo-app
spec:
  output:
    to:
      kind: ImageStreamTag
      name: dev-conf-demo-app:latest
  source:
    type: Git
    git:
      uri: https://github.com/accorvin/devconf-us-2019-demo.git
  strategy:
    type: Docker
  triggers:
    - type: ConfigChange
